name: create azure rg
on:
  workflow_dispatch
permissions:
      id-token: write 
      contents: read 
jobs:
  terraform-Job:
    name: azure-rg-create
    runs-on: vivek-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: 1.10.5

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: Environment/Prod
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: Environment/Prod

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
        working-directory: Environment/Prod

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: Environment/Prod




      
      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color
      #   working-directory: ./Environment/Dev
      

