name: "create-azure-rg"

on:
  workflow_dispatch:

jobs:
  create-resource-group:
    name: creating azure resource group
    permissions: write-all
    runs-on: self-hosted
    steps: 
      - name: vivek rocks
    
